@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmYwNDA5OWZhZDY4OWJlYmMyYmRiOCIsInRva2VuSWQiOiJNVGMwTURZek5UTTJNelkzTWc9PU9XOXFNUT09IiwiaWF0IjoxNzQwNjM1MzYzLCJleHAiOjIxMDA2MzUzNjN9.HgSX2_BdEHOPYf9bhA6iihgjwxKxaOFx5EiGSCp8wiY
@baseUrl = http://localhost:3000/store

GET {{baseUrl}}/search_suggestions?term=
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/search?term=
Authorization: Bearer {{accessToken}}

###


GET {{baseUrl}}/app/67becd0bed355017e8b5bd46
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/app/67becd0bed355017e8b5bd47/reviews?identifier=0&limit=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###


POST {{baseUrl}}/app/67becd0bed355017e8b5bd46/reviews
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "Hello this is a test review app.. good",
  "rate": 4
}

###


### Get History
GET {{baseUrl}}/history/view?identifier=9999999999999&limit=10 HTTP/1.1
Authorization: Bearer {{accessToken}}

### Delete Specific History Item
DELETE {{baseUrl}}/history/view/67c1b0d666f4ea9471e02075 HTTP/1.1
Authorization: Bearer {{accessToken}}

### Delete All History
DELETE {{baseUrl}}/history/search HTTP/1.1
Authorization: Bearer {{accessToken}}
